In [5]:
import pandas as pd 
import numpy as np

In [6]:
orders = pd.read_excel("Company ShopX - Order Report.xlsx")
weight = pd.read_excel("Company ShopX - Product Weight.xlsx")
zone = pd.read_excel("Company ShopX - Warehouse&Customer Pin Code and Zone details.xlsx")
invoice = pd.read_excel("Courier Company - Invoice.xlsx")
rates = pd.read_excel("Courier Company - Rates.xlsx")

In [7]:
print(orders.columns)
print(weight.columns)
print(zone.columns)
print(invoice.columns)
print(rates.columns)

Index(['Order ID', 'Product Code', 'Units Ordered'], dtype='object')
Index(['Product Code', 'Product Weight (g)'], dtype='object')
Index(['Store House Pincode', 'Customer Area Code', 'Delivery Zone'], dtype='object')
Index(['AWB Code (Airway Bill Number) ', 'Order ID', 'Chargeable Weight',
       'Store House Pincode', 'Customer Area Code', 'Delivery Zone',
       'Freight Type', 'Total Amount (Rs.)'],
      dtype='object')
Index(['fwd_a_fixed', 'fwd_a_additional', 'fwd_b_fixed', 'fwd_b_additional',
       'fwd_c_fixed', 'fwd_c_additional', 'fwd_d_fixed', 'fwd_d_additional',
       'fwd_e_fixed', 'fwd_e_additional', 'rto_a_fixed', 'rto_a_additional',
       'rto_b_fixed', 'rto_b_additional', 'rto_c_fixed', 'rto_c_additional',
       'rto_d_fixed', 'rto_d_additional', 'rto_e_fixed', 'rto_e_additional'],
      dtype='object')

In [8]:

print(weight.head())

    Product Code  Product Weight (g)
0  8904223815682                 210
1  8904223815859                 165
2  8904223815866                 113
3  8904223815873                  65
4  8904223816214                 120

In [9]:
print(orders.head())

     Order ID   Product Code  Units Ordered
0  2001827036  8904223818706            1.0
1  2001827036  8904223819093            1.0
2  2001827036  8904223819109            1.0
3  2001827036  8904223818430            1.0
4  2001827036  8904223819277            1.0

In [10]:
df = pd.merge(orders, weight, on="Product Code")
df

       Order ID   Product Code  Units Ordered  Product Weight (g)
0    2001827036  8904223818706            1.0                 127
1    2001827036  8904223819093            1.0                 150
2    2001827036  8904223819109            1.0                 100
3    2001827036  8904223818430            1.0                 165
4    2001827036  8904223819277            1.0                 350
..          ...            ...            ...                 ...
396  2001806229  8904223818942            1.0                 133
397  2001806229  8904223818850            1.0                 240
398  2001806226  8904223818850            2.0                 240
399  2001806210  8904223816214            1.0                 120
400  2001806210  8904223818874            1.0                 100

[401 rows x 4 columns]

In [11]:
df["Total Weight (g)"] = df["Product Weight (g)"] *df["Units Ordered"]

In [12]:
df

,Order ID,Product Code,Units Ordered,Product Weight (g),Total Weight (g)
0,2001827036,8904223818706,1.0,127,127.0
1,2001827036,8904223819093,1.0,150,150.0
2,2001827036,8904223819109,1.0,100,100.0
3,2001827036,8904223818430,1.0,165,165.0
4,2001827036,8904223819277,1.0,350,350.0
...,...,...,...,...,...
396,2001806229,8904223818942,1.0,133,133.0
397,2001806229,8904223818850,1.0,240,240.0
398,2001806226,8904223818850,2.0,240,480.0
399,2001806210,8904223816214,1.0,120,120.0
400,2001806210,8904223818874,1.0,100,100.0

In [13]:
Order_Weight = df.groupby("Order ID")['Total Weight (g)'].sum().reset_index()

In [14]:
Order_Weight

       Order ID  Total Weight (g)
0    2001806210             220.0
1    2001806226             480.0
2    2001806229             500.0
3    2001806232            1302.0
4    2001806233             245.0
..          ...               ...
119  2001821995             477.0
120  2001822466            1376.0
121  2001823564             672.0
122  2001825261            1557.0
123  2001827036            2176.0

[124 rows x 2 columns]

In [15]:
final_df = pd.merge(Order_Weight, invoice, on="Order ID")

In [16]:
final_df

,Order ID,Total Weight (g),AWB Code (Airway Bill Number),Chargeable Weight,Store House Pincode,Customer Area Code,Delivery Zone,Freight Type,Total Amount (Rs.)
0,2001806210,220.0,1091117221940,2.92,121003,140604,b,Forward charges,174.5
1,2001806226,480.0,1091117222065,0.68,121003,723146,d,Forward charges,90.2
2,2001806229,500.0,1091117222080,0.71,121003,421204,d,Forward charges,90.2
3,2001806232,1302.0,1091117222124,1.30,121003,507101,d,Forward charges,135.0
4,2001806233,245.0,1091117222135,0.78,121003,263139,b,Forward charges,61.3
...,...,...,...,...,...,...,...,...,...
119,2001821995,477.0,1091121183730,0.50,121003,342008,d,Forward charges,45.4
120,2001822466,1376.0,1091121305541,1.10,121003,342301,d,Forward charges,135.0
121,2001823564,672.0,1091121666133,0.70,121003,492001,d,Forward and RTO charges,172.8
122,2001825261,1557.0,1091121981575,1.60,121003,517128,d,Forward and RTO charges,345.0
123,2001827036,2176.0,1091122418320,1.60,121003,173213,b,Forward charges,117.9

In [17]:
# To conver gram into KG
final_df["Total Weight (KG)"] = final_df["Total Weight (g)"] / 1000
final_df["Courier Weight (KG)"] = final_df["Chargeable Weight"]

In [18]:
final_df

,Order ID,Total Weight (g),AWB Code (Airway Bill Number),Chargeable Weight,Store House Pincode,Customer Area Code,Delivery Zone,Freight Type,Total Amount (Rs.),Total Weight (KG),Courier Weight (KG)
0,2001806210,220.0,1091117221940,2.92,121003,140604,b,Forward charges,174.5,0.220,2.92
1,2001806226,480.0,1091117222065,0.68,121003,723146,d,Forward charges,90.2,0.480,0.68
2,2001806229,500.0,1091117222080,0.71,121003,421204,d,Forward charges,90.2,0.500,0.71
3,2001806232,1302.0,1091117222124,1.30,121003,507101,d,Forward charges,135.0,1.302,1.30
4,2001806233,245.0,1091117222135,0.78,121003,263139,b,Forward charges,61.3,0.245,0.78
...,...,...,...,...,...,...,...,...,...,...,...
119,2001821995,477.0,1091121183730,0.50,121003,342008,d,Forward charges,45.4,0.477,0.50
120,2001822466,1376.0,1091121305541,1.10,121003,342301,d,Forward charges,135.0,1.376,1.10
121,2001823564,672.0,1091121666133,0.70,121003,492001,d,Forward and RTO charges,172.8,0.672,0.70
122,2001825261,1557.0,1091121981575,1.60,121003,517128,d,Forward and RTO charges,345.0,1.557,1.60
123,2001827036,2176.0,1091122418320,1.60,121003,173213,b,Forward charges,117.9,2.176,1.60

In [19]:
# Makes Slab like 2 KG so there are 4 slabs of 0.5KG
final_df["Slab Count"] = np.ceil(final_df["Total Weight (KG)"] / 0.5)

In [20]:
final_df

,Order ID,Total Weight (g),AWB Code (Airway Bill Number),Chargeable Weight,Store House Pincode,Customer Area Code,Delivery Zone,Freight Type,Total Amount (Rs.),Total Weight (KG),Courier Weight (KG),Slab Count
0,2001806210,220.0,1091117221940,2.92,121003,140604,b,Forward charges,174.5,0.220,2.92,1.0
1,2001806226,480.0,1091117222065,0.68,121003,723146,d,Forward charges,90.2,0.480,0.68,1.0
2,2001806229,500.0,1091117222080,0.71,121003,421204,d,Forward charges,90.2,0.500,0.71,1.0
3,2001806232,1302.0,1091117222124,1.30,121003,507101,d,Forward charges,135.0,1.302,1.30,3.0
4,2001806233,245.0,1091117222135,0.78,121003,263139,b,Forward charges,61.3,0.245,0.78,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
119,2001821995,477.0,1091121183730,0.50,121003,342008,d,Forward charges,45.4,0.477,0.50,1.0
120,2001822466,1376.0,1091121305541,1.10,121003,342301,d,Forward charges,135.0,1.376,1.10,3.0
121,2001823564,672.0,1091121666133,0.70,121003,492001,d,Forward and RTO charges,172.8,0.672,0.70,2.0
122,2001825261,1557.0,1091121981575,1.60,121003,517128,d,Forward and RTO charges,345.0,1.557,1.60,4.0
123,2001827036,2176.0,1091122418320,1.60,121003,173213,b,Forward charges,117.9,2.176,1.60,5.0

In [21]:
rates.columns = rates.columns.str.strip()

In [22]:
zone.head()

   Store House Pincode  Customer Area Code Delivery Zone
0               121003              507101             d
1               121003              486886             d
2               121003              532484             d
3               121003              143001             b
4               121003              515591             d

In [23]:
rates.head()

,fwd_a_fixed,fwd_a_additional,fwd_b_fixed,fwd_b_additional,fwd_c_fixed,fwd_c_additional,fwd_d_fixed,fwd_d_additional,fwd_e_fixed,fwd_e_additional,rto_a_fixed,rto_a_additional,rto_b_fixed,rto_b_additional,rto_c_fixed,rto_c_additional,rto_d_fixed,rto_d_additional,rto_e_fixed,rto_e_additional
0,29.5,23.6,33,28.3,40.1,38.9,45.4,44.8,56.6,55.5,13.6,23.6,20.5,28.3,31.9,38.9,41.3,44.8,50.7,55.5

In [24]:
def calculate_charge(row):
    slabs = row["Slab Count"]
    zone = row["Delivery Zone"].lower()   # a, b, c...
    
    # Dynamic column names
    fwd_fixed_col = f"fwd_{zone}_fixed"
    fwd_add_col = f"fwd_{zone}_additional"
    
    rto_fixed_col = f"rto_{zone}_fixed"
    rto_add_col = f"rto_{zone}_additional"
    
    # Forward charge
    charge = rates.iloc[0][fwd_fixed_col]
    
    if slabs > 1:
        charge += (slabs - 1) * rates.iloc[0][fwd_add_col]
    
    # RTO condition
    if row["Freight Type"] == "Forward and RTO charges":
        charge += rates.iloc[0][rto_fixed_col]
        
        if slabs > 1:
            charge += (slabs - 1) * rates.iloc[0][rto_add_col]
    
    return charge

In [25]:
final_df["Expected Charge (Rs.)"] = final_df.apply(calculate_charge, axis=1)

In [26]:
final_df

,Order ID,Total Weight (g),AWB Code (Airway Bill Number),Chargeable Weight,Store House Pincode,Customer Area Code,Delivery Zone,Freight Type,Total Amount (Rs.),Total Weight (KG),Courier Weight (KG),Slab Count,Expected Charge (Rs.)
0,2001806210,220.0,1091117221940,2.92,121003,140604,b,Forward charges,174.5,0.220,2.92,1.0,33.0
1,2001806226,480.0,1091117222065,0.68,121003,723146,d,Forward charges,90.2,0.480,0.68,1.0,45.4
2,2001806229,500.0,1091117222080,0.71,121003,421204,d,Forward charges,90.2,0.500,0.71,1.0,45.4
3,2001806232,1302.0,1091117222124,1.30,121003,507101,d,Forward charges,135.0,1.302,1.30,3.0,135.0
4,2001806233,245.0,1091117222135,0.78,121003,263139,b,Forward charges,61.3,0.245,0.78,1.0,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,2001821995,477.0,1091121183730,0.50,121003,342008,d,Forward charges,45.4,0.477,0.50,1.0,45.4
120,2001822466,1376.0,1091121305541,1.10,121003,342301,d,Forward charges,135.0,1.376,1.10,3.0,135.0
121,2001823564,672.0,1091121666133,0.70,121003,492001,d,Forward and RTO charges,172.8,0.672,0.70,2.0,176.3
122,2001825261,1557.0,1091121981575,1.60,121003,517128,d,Forward and RTO charges,345.0,1.557,1.60,4.0,355.5
123,2001827036,2176.0,1091122418320,1.60,121003,173213,b,Forward charges,117.9,2.176,1.60,5.0,146.2

In [27]:
final_df["Difference (Rs.)"] = final_df["Total Amount (Rs.)"] - final_df["Expected Charge (Rs.)"]
final_df

,Order ID,Total Weight (g),AWB Code (Airway Bill Number),Chargeable Weight,Store House Pincode,Customer Area Code,Delivery Zone,Freight Type,Total Amount (Rs.),Total Weight (KG),Courier Weight (KG),Slab Count,Expected Charge (Rs.),Difference (Rs.)
0,2001806210,220.0,1091117221940,2.92,121003,140604,b,Forward charges,174.5,0.220,2.92,1.0,33.0,141.5
1,2001806226,480.0,1091117222065,0.68,121003,723146,d,Forward charges,90.2,0.480,0.68,1.0,45.4,44.8
2,2001806229,500.0,1091117222080,0.71,121003,421204,d,Forward charges,90.2,0.500,0.71,1.0,45.4,44.8
3,2001806232,1302.0,1091117222124,1.30,121003,507101,d,Forward charges,135.0,1.302,1.30,3.0,135.0,0.0
4,2001806233,245.0,1091117222135,0.78,121003,263139,b,Forward charges,61.3,0.245,0.78,1.0,33.0,28.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,2001821995,477.0,1091121183730,0.50,121003,342008,d,Forward charges,45.4,0.477,0.50,1.0,45.4,0.0
120,2001822466,1376.0,1091121305541,1.10,121003,342301,d,Forward charges,135.0,1.376,1.10,3.0,135.0,0.0
121,2001823564,672.0,1091121666133,0.70,121003,492001,d,Forward and RTO charges,172.8,0.672,0.70,2.0,176.3,-3.5
122,2001825261,1557.0,1091121981575,1.60,121003,517128,d,Forward and RTO charges,345.0,1.557,1.60,4.0,355.5,-10.5
123,2001827036,2176.0,1091122418320,1.60,121003,173213,b,Forward charges,117.9,2.176,1.60,5.0,146.2,-28.3

In [28]:
final_df["Weight slab as per ShopX (KG)"] = np.ceil(final_df["Total Weight (KG)"] / 0.5) * 0.5
final_df["Weight slab charged by Courier (KG)"] = np.ceil(final_df["Courier Weight (KG)"] / 0.5) * 0.5
final_df

,Order ID,Total Weight (g),AWB Code (Airway Bill Number),Chargeable Weight,Store House Pincode,Customer Area Code,Delivery Zone,Freight Type,Total Amount (Rs.),Total Weight (KG),Courier Weight (KG),Slab Count,Expected Charge (Rs.),Difference (Rs.),Weight slab as per ShopX (KG),Weight slab charged by Courier (KG)
0,2001806210,220.0,1091117221940,2.92,121003,140604,b,Forward charges,174.5,0.220,2.92,1.0,33.0,141.5,0.5,3.0
1,2001806226,480.0,1091117222065,0.68,121003,723146,d,Forward charges,90.2,0.480,0.68,1.0,45.4,44.8,0.5,1.0
2,2001806229,500.0,1091117222080,0.71,121003,421204,d,Forward charges,90.2,0.500,0.71,1.0,45.4,44.8,0.5,1.0
3,2001806232,1302.0,1091117222124,1.30,121003,507101,d,Forward charges,135.0,1.302,1.30,3.0,135.0,0.0,1.5,1.5
4,2001806233,245.0,1091117222135,0.78,121003,263139,b,Forward charges,61.3,0.245,0.78,1.0,33.0,28.3,0.5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,2001821995,477.0,1091121183730,0.50,121003,342008,d,Forward charges,45.4,0.477,0.50,1.0,45.4,0.0,0.5,0.5
120,2001822466,1376.0,1091121305541,1.10,121003,342301,d,Forward charges,135.0,1.376,1.10,3.0,135.0,0.0,1.5,1.5
121,2001823564,672.0,1091121666133,0.70,121003,492001,d,Forward and RTO charges,172.8,0.672,0.70,2.0,176.3,-3.5,1.0,1.0
122,2001825261,1557.0,1091121981575,1.60,121003,517128,d,Forward and RTO charges,345.0,1.557,1.60,4.0,355.5,-10.5,2.0,2.0
123,2001827036,2176.0,1091122418320,1.60,121003,173213,b,Forward charges,117.9,2.176,1.60,5.0,146.2,-28.3,2.5,2.0

In [29]:
def status(x):
    if x == 0:
        return "Correct"
    elif x > 0:
        return "Overcharged"
    else:
        return "Undercharged"

final_df["Status"] = final_df["Difference (Rs.)"].apply(status)

In [30]:
final_df

,Order ID,Total Weight (g),AWB Code (Airway Bill Number),Chargeable Weight,Store House Pincode,Customer Area Code,Delivery Zone,Freight Type,Total Amount (Rs.),Total Weight (KG),Courier Weight (KG),Slab Count,Expected Charge (Rs.),Difference (Rs.),Weight slab as per ShopX (KG),Weight slab charged by Courier (KG),Status
0,2001806210,220.0,1091117221940,2.92,121003,140604,b,Forward charges,174.5,0.220,2.92,1.0,33.0,141.5,0.5,3.0,Overcharged
1,2001806226,480.0,1091117222065,0.68,121003,723146,d,Forward charges,90.2,0.480,0.68,1.0,45.4,44.8,0.5,1.0,Overcharged
2,2001806229,500.0,1091117222080,0.71,121003,421204,d,Forward charges,90.2,0.500,0.71,1.0,45.4,44.8,0.5,1.0,Overcharged
3,2001806232,1302.0,1091117222124,1.30,121003,507101,d,Forward charges,135.0,1.302,1.30,3.0,135.0,0.0,1.5,1.5,Correct
4,2001806233,245.0,1091117222135,0.78,121003,263139,b,Forward charges,61.3,0.245,0.78,1.0,33.0,28.3,0.5,1.0,Overcharged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,2001821995,477.0,1091121183730,0.50,121003,342008,d,Forward charges,45.4,0.477,0.50,1.0,45.4,0.0,0.5,0.5,Correct
120,2001822466,1376.0,1091121305541,1.10,121003,342301,d,Forward charges,135.0,1.376,1.10,3.0,135.0,0.0,1.5,1.5,Correct
121,2001823564,672.0,1091121666133,0.70,121003,492001,d,Forward and RTO charges,172.8,0.672,0.70,2.0,176.3,-3.5,1.0,1.0,Undercharged
122,2001825261,1557.0,1091121981575,1.60,121003,517128,d,Forward and RTO charges,345.0,1.557,1.60,4.0,355.5,-10.5,2.0,2.0,Undercharged
123,2001827036,2176.0,1091122418320,1.60,121003,173213,b,Forward charges,117.9,2.176,1.60,5.0,146.2,-28.3,2.5,2.0,Undercharged

# Summary Table

In [31]:
correct = final_df[final_df["Status"]=="Correct"]
over = final_df[final_df["Status"]=="Overcharged"]
under = final_df[final_df["Status"]=="Undercharged"]

In [32]:
summary = pd.DataFrame({
    'Type': ['Correct','Overcharged','Undercharged'],
    'Count': [len(correct), len(over), len(under)],
    'Amount': [correct['Expected Charge (Rs.)'].sum(),
               over['Difference (Rs.)'].sum(),
               under['Difference (Rs.)'].sum() * -1]
})

In [33]:
summary

           Type  Count  Amount
0       Correct     30  2400.5
1   Overcharged     72  3140.8
2  Undercharged     22   497.0

In [34]:
final_df[final_df["Status"]=="Undercharged"].reset_index()

,index,Order ID,Total Weight (g),AWB Code (Airway Bill Number),Chargeable Weight,Store House Pincode,Customer Area Code,Delivery Zone,Freight Type,Total Amount (Rs.),Total Weight (KG),Courier Weight (KG),Slab Count,Expected Charge (Rs.),Difference (Rs.),Weight slab as per ShopX (KG),Weight slab charged by Courier (KG),Status
0,40,2001807362,2016.0,1091117324394,2.00,121003,452018,d,Forward charges,179.8,2.016,2.00,5.0,224.6,-4.480000e+01,2.5,2.0,Undercharged
1,41,2001807415,1048.0,1091117325094,1.00,121003,208001,b,Forward charges,61.3,1.048,1.00,3.0,89.6,-2.830000e+01,1.5,1.0,Undercharged
2,51,2001807976,721.0,1091117327496,0.70,121003,400705,d,Forward and RTO charges,172.8,0.721,0.70,2.0,176.3,-3.500000e+00,1.0,1.0,Undercharged
3,57,2001808295,245.0,1091117435661,0.20,121003,673002,e,Forward and RTO charges,107.3,0.245,0.20,1.0,107.3,-1.421085e-14,0.5,0.5,Undercharged
4,71,2001809383,607.0,1091117614452,0.50,121003,303702,d,Forward and RTO charges,86.7,0.607,0.50,2.0,176.3,-8.960000e+01,1.0,0.5,Undercharged
5,72,2001809592,1505.0,1091117616121,1.50,121003,244713,b,Forward charges,89.6,1.505,1.50,4.0,117.9,-2.830000e+01,2.0,1.5,Undercharged
6,73,2001809794,1517.0,1091117795531,1.50,121003,580007,d,Forward charges,135.0,1.517,1.50,4.0,179.8,-4.480000e+01,2.0,1.5,Undercharged
7,74,2001809820,3080.0,1091117795623,3.00,121003,360005,d,Forward charges,269.4,3.080,3.00,7.0,314.2,-4.480000e+01,3.5,3.0,Undercharged
8,75,2001809917,630.0,1091121482593,0.60,121003,831006,d,Forward and RTO charges,172.8,0.630,0.60,2.0,176.3,-3.500000e+00,1.0,1.0,Undercharged
9,85,2001811192,1032.0,1091117957780,1.13,121003,562110,d,Forward and RTO charges,258.9,1.032,1.13,3.0,265.9,-7.000000e+00,1.5,1.5,Undercharged
10,87,2001811305,750.0,1091121846136,0.50,121003,302020,d,Forward charges,45.4,0.750,0.50,2.0,90.2,-4.480000e+01,1.0,0.5,Undercharged
11,91,2001811475,689.0,1091121844806,0.50,121003,173212,b,Forward charges,33.0,0.689,0.50,2.0,61.3,-2.830000e+01,1.0,0.5,Undercharged
12,96,2001812838,558.0,1091118547832,0.60,121003,262405,b,Forward and RTO charges,102.3,0.558,0.60,2.0,110.1,-7.800000e+00,1.0,1.0,Undercharged
13,103,2001816684,920.0,1091119398844,0.99,121003,394210,d,Forward and RTO charges,172.8,0.920,0.99,2.0,176.3,-3.500000e+00,1.0,1.0,Undercharged
14,105,2001817093,1357.0,1091121485824,1.30,121003,244001,b,Forward and RTO charges,151.1,1.357,1.30,3.0,166.7,-1.560000e+01,1.5,1.5,Undercharged
15,106,2001817160,700.0,1091119630264,0.70,121003,411014,d,Forward and RTO charges,172.8,0.700,0.70,2.0,176.3,-3.500000e+00,1.0,1.0,Undercharged
16,107,2001818390,841.0,1091120014461,0.80,121003,783301,e,Forward and RTO charges,213.5,0.841,0.80,2.0,218.3,-4.800000e+00,1.0,1.0,Undercharged
17,110,2001820978,515.0,1091120922803,0.50,121003,313301,d,Forward charges,45.4,0.515,0.50,2.0,90.2,-4.480000e+01,1.0,0.5,Undercharged
18,112,2001821190,1200.0,1091120959015,1.20,121003,486661,d,Forward and RTO charges,258.9,1.200,1.20,3.0,265.9,-7.000000e+00,1.5,1.5,Undercharged
19,121,2001823564,672.0,1091121666133,0.70,121003,492001,d,Forward and RTO charges,172.8,0.672,0.70,2.0,176.3,-3.500000e+00,1.0,1.0,Undercharged
20,122,2001825261,1557.0,1091121981575,1.60,121003,517128,d,Forward and RTO charges,345.0,1.557,1.60,4.0,355.5,-1.050000e+01,2.0,2.0,Undercharged
21,123,2001827036,2176.0,1091122418320,1.60,121003,173213,b,Forward charges,117.9,2.176,1.60,5.0,146.2,-2.830000e+01,2.5,2.0,Undercharged

In [35]:
output = pd.DataFrame()

output["Order ID"] = final_df["Order ID"]
output["AWB Number"] = final_df["AWB Code (Airway Bill Number) "].astype(str)

output["Total weight as per ShopX (KG)"] = final_df["Total Weight (KG)"]
output["Weight slab as per ShopX (KG)"] = final_df["Weight slab as per ShopX (KG)"]

output["Total weight as per Courier Company (KG)"] = final_df["Courier Weight (KG)"]
output["Weight slab charged by Courier Company (KG)"] = final_df["Weight slab charged by Courier (KG)"]

output["Delivery Zone as per ShopX"] = final_df["Delivery Zone"]
output["Delivery Zone charged by Courier Company"] = final_df["Delivery Zone"]

output["Expected Charge as per ShopX (Rs.)"] = final_df["Expected Charge (Rs.)"]
output["Charges Billed by Courier Company (Rs.)"] = final_df["Total Amount (Rs.)"]

output["Difference Between Expected Charges and Billed Charges (Rs.)"] = final_df["Difference (Rs.)"].round(2)

In [36]:
output

,Order ID,AWB Number,Total weight as per ShopX (KG),Weight slab as per ShopX (KG),Total weight as per Courier Company (KG),Weight slab charged by Courier Company (KG),Delivery Zone as per ShopX,Delivery Zone charged by Courier Company,Expected Charge as per ShopX (Rs.),Charges Billed by Courier Company (Rs.),Difference Between Expected Charges and Billed Charges (Rs.)
0,2001806210,1091117221940,0.220,0.5,2.92,3.0,b,b,33.0,174.5,141.5
1,2001806226,1091117222065,0.480,0.5,0.68,1.0,d,d,45.4,90.2,44.8
2,2001806229,1091117222080,0.500,0.5,0.71,1.0,d,d,45.4,90.2,44.8
3,2001806232,1091117222124,1.302,1.5,1.30,1.5,d,d,135.0,135.0,0.0
4,2001806233,1091117222135,0.245,0.5,0.78,1.0,b,b,33.0,61.3,28.3
...,...,...,...,...,...,...,...,...,...,...,...
119,2001821995,1091121183730,0.477,0.5,0.50,0.5,d,d,45.4,45.4,0.0
120,2001822466,1091121305541,1.376,1.5,1.10,1.5,d,d,135.0,135.0,0.0
121,2001823564,1091121666133,0.672,1.0,0.70,1.0,d,d,176.3,172.8,-3.5
122,2001825261,1091121981575,1.557,2.0,1.60,2.0,d,d,355.5,345.0,-10.5
123,2001827036,1091122418320,2.176,2.5,1.60,2.0,b,b,146.2,117.9,-28.3

In [37]:
with pd.ExcelWriter("Logistic_Final_Report_20.xlsx") as writer:
    output.to_excel(writer, sheet_name="output", index=False)
    summary.to_excel(writer, sheet_name="Summary", index=False)

In [38]:
%whos

Variable               Type              Data/Info
--------------------------------------------------
NamespaceMagics        MetaHasTraits     <class 'IPython.core.magi<...>mespace.NamespaceMagics'>
Order_Weight           DataFrame         Shape: (124, 2)
calculate_charge       function          <function calculate_charge at 0x00000151D5737A60>
collections            module            <module 'collections' fro<...>ollections\\__init__.py'>
correct                DataFrame         Shape: (30, 17)
dataframe_columns      function          <function dataframe_colum<...>ns at 0x00000151D0E372E0>
dataframe_hash         function          <function dataframe_hash at 0x00000151D5736C00>
df                     DataFrame         Shape: (401, 5)
dtypes_str             function          <function dtypes_str at 0x00000151D5737BA0>
final_df               DataFrame         Shape: (124, 17)
get_dataframes         function          <function get_dataframes at 0x00000151D6000220>
get_ipython            function          <function get_ipython at 0x00000151CFF78D60>
getpass                module            <module 'getpass' from 'C<...>conda3\\Lib\\getpass.py'>
hashlib                module            <module 'hashlib' from 'C<...>conda3\\Lib\\hashlib.py'>
import_pandas_safely   function          <function import_pandas_s<...>ly at 0x00000151D0E363E0>
invoice                DataFrame         Shape: (124, 8)
is_data_frame          function          <function is_data_frame at 0x00000151D0E37A60>
islice                 type              <class 'itertools.islice'>
json                   module            <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
np                     module            <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
orders                 DataFrame         Shape: (400, 3)
output                 DataFrame         Shape: (124, 11)
over                   DataFrame         Shape: (72, 17)
pd                     module            <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
rates                  DataFrame         Shape: (1, 20)
status                 function          <function status at 0x00000151D6003600>
summary                DataFrame         Shape: (3, 3)
sys                    module            <module 'sys' (built-in)>
under                  DataFrame         Shape: (22, 17)
weight                 DataFrame         Shape: (66, 2)
writer                 OpenpyxlWriter    <pandas.io.excel._openpyx<...>ct at 0x00000151D0E146E0>
zone                   DataFrame         Shape: (124, 3)